# Clippy configuration for stricter linting
# See: https://doc.rust-lang.org/clippy/configuration.html

# Enforce documentation for public items
missing-docs-in-crate-items = true

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Type complexity threshold  
type-complexity-threshold = 250

# Too many arguments threshold
too-many-arguments-threshold = 7

# Too many lines threshold
too-many-lines-threshold = 100

# Trivial copy pass by reference threshold
trivial-copy-size-limit = 64

# Single char binding names threshold (corrected field name)
single-char-binding-names-threshold = 4

# Literal representation threshold
literal-representation-threshold = 10

# Avoid breaking exported API
avoid-breaking-exported-api = true

# Check for private items in public interface
check-private-items = true
