[[hooks]]
stage = "build"
command = "cargo"
command_arguments = ["build", "--release"]

[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true

[watch]
ignore = ["dist"]
# Removed "target" from ignore list - it doesn't exist yet and causes errors

[serve]
# Use 'addresses' instead of deprecated 'address'
addresses = ["127.0.0.1"]
port = 8080
open = true

