[package]
name = "anchor-etherlink"
version = "0.1.0"
edition = "2021"

[dependencies]
phoenix-evidence = { path = "../evidence" }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
