name: CI - Marketing (Lint, TypeCheck, Build)

on:
  push:
    branches: [main]
    paths:
      - "apps/marketing/**"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "tsconfig.base.json"
      - ".eslintrc.js"
      - ".github/workflows/ci-marketing.yml"
  pull_request:
    paths:
      - "apps/marketing/**"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "tsconfig.base.json"
      - ".eslintrc.js"
      - ".github/workflows/ci-marketing.yml"
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: TypeScript check
        run: pnpm typecheck

      - name: Build
        run: pnpm build
