name: CI - Rust

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/ci-rust.yml'
  pull_request:
    paths:
      - 'apps/api/**'
      - '.github/workflows/ci-rust.yml'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Build (workspace)
        run: cargo build --workspace --all-targets

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test
        run: cargo test --workspace --all-features --all-targets
