name: CI - Rust (Format, Lint, Test, Audit)

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'apps/keeper/**'
      - 'apps/evidence-cli/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/ci-rust.yml'
  pull_request:
    paths:
      - 'apps/api/**'
      - 'apps/keeper/**'
      - 'apps/evidence-cli/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/ci-rust.yml'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Build (workspace)
        run: cargo build --workspace --all-targets --all-features

      - name: Test
        run: cargo test --workspace --all-features --all-targets

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Security audit
        run: cargo audit
